# Generated by Django 3.2.4 on 2021-08-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountPage',
        ),
    ]
