# Generated by Django 4.0.6 on 2022-07-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todopage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-todo']},
        ),
    ]
